@include('layouts.htmlheader')
@include('layouts.webnavheader2')
         @yield('content')
@include('layouts.sectionfooter')
@include('layouts.jsfooterfront')
@include('layouts.scriptfooter2')
         @yield('customscripts')
@include('layouts.htmlfooter')
